from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
import re
from openapi_server import util

import re  # noqa: E501

class InternalServerError(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None):  # noqa: E501
        """InternalServerError - a model defined in OpenAPI

        :param message: The message of this InternalServerError.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'message': str
        }

        self.attribute_map = {
            'message': 'message'
        }

        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'InternalServerError':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InternalServerError of this InternalServerError.  # noqa: E501
        :rtype: InternalServerError
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this InternalServerError.


        :return: The message of this InternalServerError.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this InternalServerError.


        :param message: The message of this InternalServerError.
        :type message: str
        """
        if message is not None and len(message) > 255:
            raise ValueError("Invalid value for `message`, length must be less than or equal to `255`")  # noqa: E501
        if message is not None and not re.search(r'^example-[0-9a-z]+$^example-[0-9a-z]+$^example-[0-9a-z]+$', message):  # noqa: E501
            raise ValueError(r"Invalid value for `message`, must be a follow pattern or equal to `/^example-[0-9a-z]+$^example-[0-9a-z]+$^example-[0-9a-z]+$/`")  # noqa: E501

        self._message = message
