services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=0UbuFbKhdSYOpZjx
      - MYSQL_DATABASE=OpenParcel
      - FLASK_PORT=8080
      - SECRET_KEY=cPpkbCFceAnqhJkt
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOGIN_REQUIRED=true
      - DEV_SERVER=true
    depends_on:
      - mysql
      - redis
    networks:
      - OpenParcel

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend/src:/usr/share/nginx/html:ro
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - OpenParcel

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0UbuFbKhdSYOpZjx
      MYSQL_DATABASE: OpenParcel
    volumes:
      - OpenParcel_mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - OpenParcel

  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - OpenParcel_redis:/data
    ports:
      - "6379:6379"
    networks:
      - OpenParcel

volumes:
  OpenParcel_mysql:
    external: true
  OpenParcel_redis:
    external: true

networks:
  OpenParcel: